### ISSUE TITLE
Sessions are not destroyed

### ISSUE THREAD

**Issue by tionis** [solzimer/session-pouchdb-store#9]
When calling destroy() on a session it is not destroyed, due to following error:
```
TypeError: Cannot read property '_id' of undefined
    at PouchDB.<anonymous> (/home/tionis/dev/ep/webapp/node_modules/pouchdb/lib/index.js:1884:26)
    at PouchDB.<anonymous> (/home/tionis/dev/ep/webapp/node_modules/pouchdb/lib/index.js:288:21)
    at PouchDB.<anonymous> (/home/tionis/dev/ep/webapp/node_modules/argsarray/index.js:14:18)
    at /home/tionis/dev/ep/webapp/node_modules/pouchdb/lib/index.js:227:21
    at new Promise (<anonymous>)
    at PouchDB.<anonymous> (/home/tionis/dev/ep/webapp/node_modules/pouchdb/lib/index.js:214:19)
    at PouchDB.remove (/home/tionis/dev/ep/webapp/node_modules/argsarray/index.js:14:18)
    at SessionStore.destroy (/home/tionis/dev/ep/webapp/node_modules/session-pouchdb-store/lib/store.js:136:21)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

```

**Comment by tnovas** [comment]
Use version `0.2.7`

**Comment by tionis** [comment]
I can't test this solution as the project is long finished with another solution.  
This issue won't be useful anymore I think.
